import { useState } from "react";

const G = "#166534";
const BD = "#E5E7EB";

function Ic({ d, size = 16, color }) {
  return (
    <svg width={size} height={size} viewBox="0 0 24 24" fill="none"
      stroke={color || "currentColor"} strokeWidth="1.5"
      strokeLinecap="round" strokeLinejoin="round">
      <path d={d}/>
    </svg>
  );
}

const IC = {
  download: "M21 15v4a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2v-4M7 10l5 5 5-5M12 15V3",
  file:     "M14 2H6a2 2 0 0 0-2 2v16a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V8zM14 2v6h6",
  shield:   "M12 22s8-4 8-10V5l-8-3-8 3v7c0 6 8 10 8 10z",
};

const DOWNLOAD_FILES = [
  { key: "gns3", ext: ".gns3project", desc: "GNS3 project file ready to import", icon: IC.file },
  { key: "configs", ext: "configs.zip", desc: "Device startup configurations", icon: IC.file },
  { key: "requirements", ext: "requirements.json", desc: "Image filenames and device list", icon: IC.shield },
  { key: "ansible", ext: "ansible-export.zip", desc: "Ansible playbook + inventory + config templates", icon: IC.file },
];

/**
 * DownloadCards — 4 download cards + Download All button.
 * Each card: 36px gray icon + file name + file description + Download button.
 */
export default function DownloadCards({ projectName, sessionId, onDownload }) {
  const [downloading, setDownloading] = useState({});

  const handleDownload = async (key, filename) => {
    setDownloading((prev) => ({ ...prev, [key]: true }));
    try {
      await onDownload(key, filename);
    } finally {
      setDownloading((prev) => ({ ...prev, [key]: false }));
    }
  };

  const name = projectName || "network";

  return (
    <div style={{
      fontFamily: "'Geist', 'Inter', system-ui, sans-serif",
    }}>
      {/* Ansible dummy IPs warning */}
      <div style={{
        background: "#FFFBEB",
        border: "1px solid #FDE68A",
        borderRadius: 8,
        padding: "10px 14px",
        display: "flex",
        gap: 8,
        alignItems: "flex-start",
        marginBottom: 12,
        fontSize: 12,
        color: "#92400E",
        lineHeight: 1.5,
      }}>
        <span style={{ fontSize: 14, flexShrink: 0 }}>⚠️</span>
        <span>
          The Ansible files use dummy IP addresses generated by the AI. Before running the playbook on your real network, edit <code style={{ fontFamily: "monospace" }}>inventory.ini</code> to replace the dummy management IPs with your actual device IPs.
        </span>
      </div>

      {/* System message */}
      <div style={{
        background: "#F0FDF4",
        border: "1px solid #BBF7D0",
        borderRadius: 8,
        padding: "10px 14px",
        marginBottom: 12,
        display: "flex",
        alignItems: "center",
        gap: 8,
        fontSize: 13,
        color: G,
        fontWeight: 500,
      }}>
        ✅ GNS3 project generated successfully. Ready for download.
      </div>

      {/* Download cards */}
      <div style={{ display: "flex", flexDirection: "column", gap: 8, marginBottom: 12 }}>
        {DOWNLOAD_FILES.map((file) => {
          const filename = file.key === "gns3"
            ? `${name}.gns3project`
            : file.key === "configs"
              ? `${name}_configs.zip`
              : file.key === "requirements"
                ? `${name}_requirements.json`
                : `${name}_ansible-export.zip`;

          return (
            <div
              key={file.key}
              style={{
                display: "flex",
                alignItems: "center",
                gap: 12,
                padding: "12px 14px",
                background: "white",
                border: `1px solid ${BD}`,
                borderRadius: 10,
              }}
            >
              {/* 36px gray icon */}
              <div style={{
                width: 36, height: 36, borderRadius: 8,
                background: "rgba(22,101,52,0.07)",
                display: "flex", alignItems: "center", justifyContent: "center",
                color: "#9CA3AF", flexShrink: 0,
              }}>
                <Ic d={file.icon} size={17}/>
              </div>

              {/* File info */}
              <div style={{ flex: 1 }}>
                <div style={{ fontSize: 13, fontWeight: 600, color: "#111" }}>{filename}</div>
                <div style={{ fontSize: 12, color: "#6B7280" }}>{file.desc}</div>
              </div>

              {/* Download button */}
              <button
                onClick={() => handleDownload(file.key, filename)}
                disabled={downloading[file.key]}
                style={{
                  padding: "6px 14px",
                  border: `1px solid ${BD}`,
                  background: "white",
                  borderRadius: 8,
                  fontSize: 12,
                  fontWeight: 600,
                  color: downloading[file.key] ? "#9CA3AF" : G,
                  cursor: downloading[file.key] ? "not-allowed" : "pointer",
                  fontFamily: "inherit",
                  transition: "all .15s",
                  whiteSpace: "nowrap",
                }}
                onMouseOver={(e) => {
                  if (!downloading[file.key]) {
                    e.currentTarget.style.background = "#F0FDF4";
                    e.currentTarget.style.borderColor = "#BBF7D0";
                  }
                }}
                onMouseOut={(e) => {
                  e.currentTarget.style.background = "white";
                  e.currentTarget.style.borderColor = BD;
                }}
              >
                {downloading[file.key] ? "Downloading..." : "Download"}
              </button>
            </div>
          );
        })}
      </div>

      {/* Download All */}
      <button
        onClick={() => DOWNLOAD_FILES.forEach((f) => handleDownload(f.key, ""))}
        style={{
          width: "100%",
          padding: "10px",
          border: `1px solid ${BD}`,
          background: "white",
          borderRadius: 8,
          fontSize: 13,
          fontWeight: 600,
          color: G,
          cursor: "pointer",
          fontFamily: "inherit",
          transition: "all .15s",
        }}
        onMouseOver={(e) => {
          e.currentTarget.style.background = "#F0FDF4";
          e.currentTarget.style.borderColor = "#BBF7D0";
        }}
        onMouseOut={(e) => {
          e.currentTarget.style.background = "white";
          e.currentTarget.style.borderColor = BD;
        }}
      >
        Download All
      </button>
    </div>
  );
}
